CREATE TABLE viagem (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    destino VARCHAR(255) NOT NULL,
    data_ida DATE NOT NULL,
    data_volta DATE,
    descricao TEXT,
    status ENUM('PLANEJADA', 'ANDAMENTO', 'CONCLUIDA'),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultima_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);